<a href="https://colab.research.google.com/github/Gculb/Odin-Recipes/blob/main/Google_Project_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np  
import pandas as pd   
import matplotlib as plt 
import descartes
import plotly.express as px

import os

In [5]:
from google.colab import files
uploaded = files.upload()

Saving Bike_Data.csv to Bike_Data.csv

In [6]:
import io
df = pd.read_csv(io.BytesIO(uploaded['Bike_Data.csv']))

In [7]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_type,trip_time (min)
0,600CFD130D0FD2A4,electric_bike,17:27:53,17:35:15,NaN,NaN,NaN,NaN,41.89,-87.62,41.91,-87.62,casual,0:07:22
1,F5E6B5C1682C6464,electric_bike,18:39:52,18:47:28,NaN,NaN,NaN,NaN,41.91,-87.62,41.93,-87.63,casual,0:07:36
2,B6EB6D27BAD771D2,electric_bike,11:49:25,12:02:54,NaN,NaN,NaN,NaN,41.91,-87.65,41.89,-87.61,casual,0:13:29
3,C9C320375DE1D5C6,electric_bike,11:15:25,11:19:43,NaN,NaN,NaN,NaN,41.80,-87.66,41.80,-87.65,casual,0:04:18
4,56C055851023BE98,electric_bike,23:36:50,23:45:17,NaN,NaN,NaN,NaN,41.91,-87.63,41.93,-87.64,casual,0:08:27

In [ ]:
tripTime = df.loc[:,"trip_time (min)"]

In [ ]:
pd.isna(df['trip_time (min)'])

0         False
1         False
2         False
3         False
4         False
          ...
769199    False
769200    False
769201    False
769202    False
769203    False
Name: trip_time (min), Length: 769204, dtype: bool

In [ ]:
df.drop(['start_station_name','end_station_name','start_station_id','end_station_id','end_station_id'], axis=1)

,ride_id,rideable_type,started_at,ended_at,start_lat,start_lng,end_lat,end_lng,member_type,trip_time (min)
0,600CFD130D0FD2A4,electric_bike,17:27:53,17:35:15,41.890000,-87.620000,41.910000,-87.620000,casual,0:07:22
1,F5E6B5C1682C6464,electric_bike,18:39:52,18:47:28,41.910000,-87.620000,41.930000,-87.630000,casual,0:07:36
2,B6EB6D27BAD771D2,electric_bike,11:49:25,12:02:54,41.910000,-87.650000,41.890000,-87.610000,casual,0:13:29
3,C9C320375DE1D5C6,electric_bike,11:15:25,11:19:43,41.800000,-87.660000,41.800000,-87.650000,casual,0:04:18
4,56C055851023BE98,electric_bike,23:36:50,23:45:17,41.910000,-87.630000,41.930000,-87.640000,casual,0:08:27
...,...,...,...,...,...,...,...,...,...,...
769199,7B3B2890CA85E05D,classic_bike,0:56:48,1:01:39,41.910522,-87.653106,41.910522,-87.653106,annual,0:04:51
769200,1E993989CC66BCBC,classic_bike,0:56:25,1:00:26,41.910522,-87.653106,41.910522,-87.653106,annual,0:04:01
769201,AEA166296BC67566,electric_bike,12:47:12,12:47:36,41.920000,-87.700000,41.920000,-87.700000,casual,0:00:24
769202,B9F527742959CF03,classic_bike,13:28:46,13:53:11,41.884576,-87.631890,41.884576,-87.631890,casual,0:24:25
769203,D241310352E26484,classic_bike,14:40:51,15:08:14,41.857556,-87.661535,41.857556,-87.661535,casual,0:27:23

In [ ]:
print(df['rideable_type'].value_counts())

classic_bike     406660
electric_bike    331904
docked_bike       30640
Name: rideable_type, dtype: int64

In [ ]:
print(df['member_type'].value_counts())

annual    400153
casual    369051
Name: member_type, dtype: int64

In [ ]:
print(df['trip_time (min)'].value_counts(dropna=True))

0:07:08     772
0:05:23     771
0:06:38     766
0:06:19     766
0:05:35     762
           ...
4:01:35       1
14:30:01      1
4:53:18       1
11:45:21      1
3:13:17       1
Name: trip_time (min), Length: 11928, dtype: int64

In [ ]:
print(df.dropna(axis=1, how='all'))

                 ride_id  rideable_type started_at  ended_at  \
0       600CFD130D0FD2A4  electric_bike   17:27:53  17:35:15
1       F5E6B5C1682C6464  electric_bike   18:39:52  18:47:28
2       B6EB6D27BAD771D2  electric_bike   11:49:25  12:02:54
3       C9C320375DE1D5C6  electric_bike   11:15:25  11:19:43
4       56C055851023BE98  electric_bike   23:36:50  23:45:17
...                  ...            ...        ...       ...
769199  7B3B2890CA85E05D   classic_bike    0:56:48   1:01:39
769200  1E993989CC66BCBC   classic_bike    0:56:25   1:00:26
769201  AEA166296BC67566  electric_bike   12:47:12  12:47:36
769202  B9F527742959CF03   classic_bike   13:28:46  13:53:11
769203  D241310352E26484   classic_bike   14:40:51  15:08:14

                   start_station_name start_station_id  \
0                                 NaN              NaN
1                                 NaN              NaN
2                                 NaN              NaN
3                                 NaN              NaN
4                                 NaN              NaN
...                               ...              ...
769199   Sheffield Ave & Kingsbury St            13154
769200   Sheffield Ave & Kingsbury St            13154
769201  Milwaukee Ave & Fullerton Ave              428
769202         Clark St & Randolph St     TA1305000030
769203      Blue Island Ave & 18th St            13135

                     end_station_name end_station_id  start_lat  start_lng  \
0                                 NaN            NaN  41.890000 -87.620000
1                                 NaN            NaN  41.910000 -87.620000
2                                 NaN            NaN  41.910000 -87.650000
3                                 NaN            NaN  41.800000 -87.660000
4                                 NaN            NaN  41.910000 -87.630000
...                               ...            ...        ...        ...
769199   Sheffield Ave & Kingsbury St          13154  41.910522 -87.653106
769200   Sheffield Ave & Kingsbury St          13154  41.910522 -87.653106
769201  Milwaukee Ave & Fullerton Ave            428  41.920000 -87.700000
769202         Clark St & Randolph St   TA1305000030  41.884576 -87.631890
769203      Blue Island Ave & 18th St          13135  41.857556 -87.661535

          end_lat    end_lng member_type trip_time (min)
0       41.910000 -87.620000      casual         0:07:22
1       41.930000 -87.630000      casual         0:07:36
2       41.890000 -87.610000      casual         0:13:29
3       41.800000 -87.650000      casual         0:04:18
4       41.930000 -87.640000      casual         0:08:27
...           ...        ...         ...             ...
769199  41.910522 -87.653106      annual         0:04:51
769200  41.910522 -87.653106      annual         0:04:01
769201  41.920000 -87.700000      casual         0:00:24
769202  41.884576 -87.631890      casual         0:24:25
769203  41.857556 -87.661535      casual         0:27:23

[769204 rows x 14 columns]

In [30]:
px.set_mapbox_access_token(open("Bike_Data.csv").read())
fig = px.scatter_mapbox(df,
                        lat=df['start_lat'],
                        lon=df['start_lng'],
                        hover_name = 'start_lat',
                        height = 1000, width = 1000)
fig.show()